config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root :to => 'users#show', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  # creating a route for the API
  namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts, format: :json do 
          resources :comments, format: :json 
        end
      end
    end
  end

  # will match a GET request to the given URL and send it to the show action in the UsersController.
  get 'users/:id' => 'users#show', as: "user"

  # will match a GET/POST request to the given URL and send it to the corresponding action in the PostsController.
  get 'users/:author_id/posts/new' => 'posts#new', as: "post_new"
  post 'users/:author_id/posts/new' => 'posts#create', as: "post"
  get 'users/:author_id/posts' => 'posts#index', as: "user_posts"
  get 'users/:author_id/posts/:id' => 'posts#show', as: "user_post"
  delete 'users/:author_id/posts/:id' => 'posts#destroy'

  # will match a GET/POST request to the given URL and send it to the corresponding action in the CommentsController.
  get 'users/:author_id/posts/:id/comments/new' => 'comments#new', as: "comments_new"
  post 'users/:author_id/posts/:id/comments' => 'comments#create', as: "comment"
  delete 'users/:author_id/posts/:id/comments/:comment_id' => 'comments#destroy', as: "comment_destroy"

  # will match a GET request to the given URL and send it to the create action in the LikesController.
  get 'users/:author_id/posts/:id/likes/new' => 'likes#create', as: "likes_create"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == 'admin'
      can :manage, :all
    else
      can :destroy, Post do |post|
        post.author == user
      end
      can :destroy, Comment do |comment|
        comment.author == user
      end
      can :create, Post
      can :create, Comment
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter
  after_destroy :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  after_save :update_posts_counter
  after_destroy :update_posts_counter

  validates :title, presence: true, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.includes(:author).order(created_at: :asc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :likes, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::Base
      respond_to :json
    end
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < ApplicationController
      def index
        @user = User.find(params[:author_id])
        render json: comments, status: :ok
      end

      def create
        @post = @user.posts.find(params[:id])
        @comment = @post.comments.create(text: comment_params[:text], author_id: current_user.id, post_id: @post.id)
        if @comment.save
          render json: @comment
        else
          render error: { error: 'Unable to create comments' }, status: 400
        end
      end

      def comment_params
        params.permit(:text)
      end
    end
  end
end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
      def index
        @user = User.find(params[:author_id])
        @posts = Post.find_by(author: @user)
        render json: @posts, status: 200
      end

      def create
        @post = Post.new(author: current_user, title: params[:title], text: params[:text])
        if @post.save
          render json: { response: 'post created successfully' }, status: 200
        else
          render error: { error: 'Post not created' }, status: 400
        end
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email name])
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(post_id: params[:id], author: current_user, text: params[:text])
    if @comment.save
      redirect_to user_post_path(current_user.id, params[:id])
    else
      render :new, alert: 'Error: Comment not saved.'
    end
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @comment.destroy
    redirect_to user_post_path(params[:author_id], params[:id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(post_id: params[:id], author: current_user)
    return unless @like.save

    redirect_to user_post_path(current_user.id, params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:author_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(author: current_user, title: params[:title], text: params[:text])
    @post.author = current_user
    if @post.save
      redirect_to user_posts_path(id: @post.author_id)
    else
      render :new, alert: 'Error: Post not saved.'
    end
  end

  def show
    @user = User.find(params[:author_id])
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(request.parameters[:id])
    @post.destroy
    redirect_to user_posts_path(params[:author_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<div class="createpost-container">
<h2>New comment</h2>
<div class="form-input">
<%= form_with model: @comments, url: comment_path do |form| %>
  <%= form.text_field :text %>
</div>
<a class="createpost-btn">
  <%= form.submit "Post Comment" %>
  </a>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WordSmiths</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= render "shared/title" %>
<div class="posts-container">
    <div class="user-card">
            <img class="user-img" src=<%= @user.photo %> alt=<%= @user.name %>>
            <div class="user-card__content">
                <h3 class="user-name"><%= @user.name %></h3>
                <div class="postscount">
                    <p>Number of posts: <%= @user.posts.count %></p>
                </div>
            </div>
        </div>
    <% @user.recent_posts.each do |post| %>
    <a href=<%= user_post_path(@user.id, post.id) %>>
        <div class="user-post__item">
            <div class="user-post__content">
                <h4><%= post.title %></h4>
                <p><%= post.text[0..150] %></p>
                <div class="postscount">
                    <span>Comments: <%= post.comments_counter %>,</span>
                    <span>Likes: <%= post.likes_counter %></span>
                </div>
            </div>
        <div>
        </a>
        <div class="user-comment__item">
                <% post.recent_comments.each do |comment| %>
                <div class="user-comment__content">
                            <b><%= comment.author.name %></b>
                            <span class="comment-date"><%= comment.created_at %></span>
                </div>
                            <p class="comment"><%= comment.text %></p>
                <% end %>
                </div>
        <% end %>
</div>
<a class="allposts">
<button class="allposts-btn pagination">
        Pagination
</button></a>

app/views/posts/new.html.erb
<%= render "shared/title" %>
<div class="createpost-container">
<h2>New Post</h2>
<div class="form-input">
    <%= form_with model: @posts do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div> 
    <div>
        <%= form.label :text %>
        <%= form.text_field :text %>
    </div>
    </div>
    <a class="createpost-btn">
        <%= form.submit "Create Post" %>
    </a>
    <% end %>
</div>

app/views/posts/show.html.erb
<%= render "shared/title" %>
<div class="post-container">
<div class="user-post__content">
    <h3><%= @post.title %><span class="author"> by <%= @user.name %></span></h3>
    <div class="postscount">
                    <span>Comments: <%= @post.comments_counter %>,</span>
                    <span>Likes: <%= @post.likes_counter %></span>
                </div>
    <p><%= @post.text %></p>
    </div>
    <div class="user-comment__item">
                <% @post.comments.each do |comment| %>
                <div class="user-comment__content">
                            <b><%= User.find(comment.author_id).name %></b>
                            <span class="comment-date"><%= comment.created_at %></span>
                            <% if can? :destroy, @post %>
<%= button_to "Delete", comment_destroy_path(@user, @post, comment.id), method: :delete %>
<% end %>
                            
                </div>
                            <p class="comment"><%= comment.text %></p>
                <% end %>
                </div>
    </div>
</div>
<div class="user-action">

<% if can? :destroy, @post %>
    <%= button_to 'Delete', user_post_path(@user.id, @post.id), :method => :delete, class: 'comment-btn', style: 'background-color: red' %>
<% end %>

<%= link_to 'Like ', "#{request.url}/likes/new", class:"like-btn" %>

<a href="/users/<%= @user.id %>/posts/<%= @post.id %>/comments/new">
<button class="comment-btn">
        Add comment
</button></a>
</div>

app/views/shared/_title.html.erb
<div class="title-container">
<h1 class="title">WordSmiths</h1>
</div>

app/views/users/index.html.erb
<%= render "shared/title" %>
<div class="main-container">
<div class="about-container">
<h2 class="about-container__tagline">Writing Together, Growing Together</h2>
<p class="about-container__content">We are an open platform writing community dedicated to helping writers of all levels grow and succeed. Our supportive, collaborative environment encourages members to explore their creativity and create meaningful connections with other writers. Join us and become a part of our growing, vibrant community.</p>
</div>
<div class="users-container">
    <% @users.each do |user| %>
        <div class="user-card">
            <img class="user-img" src=<%= user.photo %> alt=<%= user.name %>>
            <div class="user-card__content">
                <a class="username" href="users/<%= user.id %>"><%= user.name %></a>
                <div class="postscount">
                    <p>Number of posts: <%= user.posts.count %></p>
                </div>
            </div>
        </div>
    <% end %>
</div>
</div>

app/views/users/show.html.erb
<%= render "shared/title" %>
<div class="user-container">
        <div class="user-card">
            <img class="user-img" src=<%= @user.photo %> alt=<%= @user.name %>>
            <div class="user-card__content">
                <h3 class="user-name"><%= @user.name %></h3>
                <div class="postscount">
                    <p>Number of posts: <%= @user.posts.count %></p>
                </div>
            </div>
        </div>
    <div class="user-bio">
        <h4>Bio</h4>
        <p><%= @user.bio %></p>
    </div>
        <% @user.recent_posts.each do |post| %>
        <a id="post-<%=post.id%>" href=<%= user_post_path(@user.id, post.id) %>>
        <div class="user-post__item">
            <div class="user-post__content">
                <h4><%= post.title %></h4>
                <p><%= post.text[0..150] %></p>
                <div class="postscount">
                    <span>Comments: <%= post.comments_counter %>,</span>
                    <span>Likes: <%= post.likes_counter %></span>
                </div>
            </div>
        <div>
        </a>
        <% end %>
</div>

<% if @current_user %>
<a href="/users/<%= @user.id %>/posts/new">
<button class="allposts-btn">
        Create new post
</button></a>
<% end %>

<a href="/users/<%= @user.id %>/posts">
<button class="allposts-btn">
        See all posts
</button></a>